version: '3'

services:
  simple_app:
    image: ab9er/simple_app:${TAG:-latest}
    container_name: simple_app
    environment:
        - FLASK_ENV=development
    env_file:
        - ./app/conf/config.env
    ports:
      - 5000:5000
    expose:
      - 3306
      - 33060
    volumes:
      - ./app:/app
    privileged: true
